// HeuristicMFCDemo.cpp : Defines the class behaviors for the application.
//
#include "stdafx.h"
#include "HeuristicMFCDemo.h"
#include "HeuristicMFCDemoDlg.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif


// CHeuristicMFCDemoApp

BEGIN_MESSAGE_MAP(CHeuristicMFCDemoApp, CWinApp)
	ON_COMMAND(ID_HELP, &CWinApp::OnHelp)
END_MESSAGE_MAP()


// CHeuristicMFCDemoApp constructor

CHeuristicMFCDemoApp::CHeuristicMFCDemoApp()
{
	// Supports restart manager
	m_dwRestartManagerSupportFlags = AFX_RESTART_MANAGER_SUPPORT_RESTART;

	// TODO: add any construction code here,
	// or place in InitInstance
}


// Unique instance of CHeuristicMFCDemoApp

CHeuristicMFCDemoApp theApp;


// CHeuristicMFCDemoApp initialization

BOOL CHeuristicMFCDemoApp::InitInstance()
{
	// If a running Windows XP application manifest specifies to enable
	// visual styles using ComCtl32.dll version 6 or higher, then InitCommonControlsEx() is required
	// so that window classes with the EX style are fully supported on servers.
	INITCOMMONCONTROLSEX InitCtrls;
	InitCtrls.dwSize = sizeof(InitCtrls);
	// Set it to be all controls compatible with Windows XP styles
	InitCtrls.dwICC = ICC_WIN95_CLASSES;
	InitCommonControlsEx(&InitCtrls);

	CWinApp::InitInstance();

	AfxEnableControlContainer();

	// Create shell manager, if the dialog contains any 
	//  COM class that need it.
	CShellManager *pShellManager = new CShellManager;

	SetRegistryKey(_T("Application generated by Application Wizard"));

	CHeuristicMFCDemoDlg dlg;
	m_pMainWnd = &dlg;
	INT_PTR nResponse = dlg.DoModal();
	if (nResponse == IDOK)
	{
		// TODO: Add any code here to be executed when the "OK" button is clicked
		// Place your application code before the return statement. See the main() function.
	}
	else if (nResponse == IDCANCEL)
	{
		// TODO: Add any code here to be executed when the "Cancel" button is clicked
		// Place your application code before the return statement. See the main() function.
	}

	// Clean up the shell manager.
	if (pShellManager != NULL)
	{
		delete pShellManager;
	}

	// Since the dialog has been closed, return FALSE so that the 
	//  application exits.
	return FALSE;
}
